name: Compile C Program

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc libcurl4-openssl-dev libcjson-dev -y

      - name: Compile
        run: |
          ls
          chmod u+x *
          ./configure --prefix=$HOME/myapp || cat config.log
          make clean
          make VERBOSE=1
          make install
          ls
          ls -R $HOME/myapp

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: proxychains-portable
          path: |
            proxychains4
            libproxychains.so.4
            /home/runner/myapp/**
