name: Compile C Program

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install gcc libcurl4-openssl-dev libcjson-dev -y

      - name: Compile
        run: |
          ls
          # Hanya atur permission jika diperlukan, misalnya:
          # chmod u+x script-yang-diperlukan.sh
          # Jika script configure tidak ada, sebaiknya hapus perintah berikut
          if [ -f ./configure ]; then
            ./configure --prefix=$HOME/myapp || cat config.log
          fi
          make clean
          make VERBOSE=1 LDFLAGS=-static
          ls -R .
          ls -R $HOME/myapp

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: proxychains-portable
          path: |
            $HOME/**
            /home/runner/myapp/**
